### ISSUE TITLE
2. Summary opening assumes previous knowledge

### ISSUE THREAD

**Issue by vsoch** [gasparl/citapp_pc#2]
You open with:

> This application implements two versions of the response time-based Concealed Informa-
tion Test (RT-CIT) deception detection method: a standard version that has been often
used in the recent years (Seymour, Seifert, Shafto, & Mosmann, 2000), and a recently
introduced enhanced version (Lukács, Kleinberg, & Verschuere, 2017)

referencing "the response time-based Concealed Information Test" as if I know what you
are talking about. I have no idea. I would suggest to rewrite the summary for the user 
that doesn't know what you are talking about. For example, something along an outline like:

 1. It's important to study how people recognize items (because...)
 2. Thus they developed this task called the Concealed.... (references)
 3. The task is great, but there are still pressing problems that (it's not reproducible, hard to run, etc.)
 4. Thus, to solve these issues, we created this! :)

I would rewrite the summary in that context - you can still provide some of the more 
"academic paper" sounding details of the task, but remember that the paper here is
intended for a general audience, and not a niche psychology community.

Review: https://github.com/openjournals/joss-reviews/issues/1179

**Comment by gasparl** [comment]
I revised the paper along the lines of your suggestion; mainly more detailed introduction and a screenshot of the GUI.

**Comment by gasparl** [comment]
Thank you!

As you may have seen there are several warning messages on the start page whenever any browser other than Chrome is used. In my related online experiments I did not only put warnings but actually completely disabled the task for other browsers. Always using the same browser ensures that everything works and is displayed exactly the same way; so that it would be consistent both within and across experiments/studies/individual tests. Since this is not some website for general visits but an experimental tool, this doesn't seem much of a practical limitation. (That is: for someone conducting an experiment, downloading Chrome - if not already in use - is the least of the trouble.)
I confess though that I decided on this mainly because of the time it took to each time test and make the code compatible with all browsers, which was especially and repeatedly problematic with IE. (Now I made a few quick tests; IE again doesn't work, Firefox and Opera seems fine.) Using one browser hugely simplifies this. But I also had some more nuanced issues, e.g., based on my tests, [synchronizing code execution to screen repaint](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) only seems to work well (for my timing purposes) on Chrome. In general, everything seems to work most easily and best on Chrome. And [everyone uses Chrome](https://en.wikipedia.org/wiki/File:Usage_Share_of_browsers_(updated_August_2018).png) anyway.

**Comment by vsoch** [comment]
I think it's okay that you are clear to specify the browser to use - it certainly is hard to maintain support for all of them. I was mainly curious and double checking that it wasn't an error to only specify Chrome.
